param(
    [string]$OutPath = ".\cpp\generated\counter_test_levels.js",
    [int]$Size = 100,
    [ValidateSet("bit0-only", "bit0-s0-diode", "bit0-bit1-no-c0", "c0-bit1", "full-s1")]
    [string]$Variant = "full-s1"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($Size -lt 100) {
    throw "counter-test-2 expects Size >= 100"
}

$fg = @()
$bg = @()
for ($x = 0; $x -lt $Size; $x++) {
    $fgCol = New-Object int[] $Size
    $bgCol = New-Object int[] $Size
    for ($y = 0; $y -lt $Size; $y++) {
        $fgCol[$y] = 2
        $bgCol[$y] = 0
    }
    $fg += ,$fgCol
    $bg += ,$bgCol
}

function Assert-InBounds {
    param([int]$X, [int]$Y)
    if ($X -lt 0 -or $X -ge $Size -or $Y -lt 0 -or $Y -ge $Size) {
        throw "Coordinate out of bounds: ($X,$Y)"
    }
}

function Open-Cell {
    param([int]$X, [int]$Y)
    Assert-InBounds $X $Y
    if ($fg[$X][$Y] -eq 2) { $fg[$X][$Y] = 0 }
}

function Set-Fg {
    param([int]$X, [int]$Y, [int]$Id)
    Assert-InBounds $X $Y
    $fg[$X][$Y] = $Id
}

function Set-Bg {
    param([int]$X, [int]$Y, [int]$Id)
    Assert-InBounds $X $Y
    $bg[$X][$Y] = $Id
    Open-Cell $X $Y
}

function Open-Rect {
    param([int]$X1, [int]$Y1, [int]$X2, [int]$Y2)
    for ($x = [Math]::Min($X1, $X2); $x -le [Math]::Max($X1, $X2); $x++) {
        for ($y = [Math]::Min($Y1, $Y2); $y -le [Math]::Max($Y1, $Y2); $y++) {
            Open-Cell $x $y
        }
    }
}

function Open-HvPath {
    param([int]$X1, [int]$Y1, [int]$X2, [int]$Y2)
    for ($x = [Math]::Min($X1, $X2); $x -le [Math]::Max($X1, $X2); $x++) {
        Open-Cell $x $Y1
    }
    for ($y = [Math]::Min($Y1, $Y2); $y -le [Math]::Max($Y1, $Y2); $y++) {
        Open-Cell $X2 $y
    }
}

function Add-Bit {
    param([int]$Off, [int]$Base)
    $open = @(
        @(3,7),@(3,6),@(3,5),@(3,4),@(3,3),
        @(4,3),@(4,4),@(4,5),
        @(5,4),@(5,5),
        @(6,4),@(6,5),
        @(4,2),@(4,1),@(5,1),@(6,1),
        @(5,2),@(6,2),
        @(6,3)
    )
    foreach ($p in $open) {
        Open-Cell ($Off + $p[0]) ($Base + $p[1])
    }

    Set-Bg ($Off + 4) ($Base + 4) 3
    Set-Bg ($Off + 5) ($Base + 4) 3
    Set-Bg ($Off + 3) ($Base + 5) 2
    Set-Fg ($Off + 4) ($Base + 4) 101
}

function Add-Diode {
    param([int]$Sx, [int]$Sy)
    $open = @(
        @(0,0),
        @(1,0),@(1,1),@(1,2),
        @(2,1),@(2,2),
        @(3,1),@(3,2),
        @(4,1),@(4,2),
        @(5,1),@(5,2),@(5,0),@(5,-1),@(5,-2)
    )
    foreach ($p in $open) {
        Open-Cell ($Sx + $p[0]) ($Sy + $p[1])
    }
    Set-Bg ($Sx + 1) $Sy 2
    Set-Bg ($Sx + 5) ($Sy - 2) 2
    Set-Bg ($Sx + 5) ($Sy - 1) 3
}

function Connect-Diode {
    param([int]$Sx, [int]$Sy, [int]$Tx, [int]$Ty)
    Add-Diode $Sx $Sy
    Open-HvPath ($Sx + 5) ($Sy - 2) $Tx $Ty
}

function Add-Start {
    Open-Cell 11 17
    Open-Cell 11 18
    Set-Fg 11 17 1
    Set-Fg 11 18 101
}

function Add-HoldEnemy {
    Open-Cell 95 10
    Open-Cell 95 11
    Set-Fg 95 10 11
    Set-Fg 95 11 101
}

Add-Bit 8 10
Add-Start
Add-HoldEnemy

if ($Variant -in @("bit0-bit1-no-c0", "c0-bit1", "full-s1")) {
    Add-Bit 60 10
}

if ($Variant -in @("bit0-s0-diode", "bit0-bit1-no-c0", "c0-bit1", "full-s1")) {
    Connect-Diode 12 11 11 17
}

if ($Variant -in @("c0-bit1", "full-s1")) {
    Connect-Diode 13 14 63 17
}

if ($Variant -eq "full-s1") {
    Connect-Diode 64 11 11 17
}

function Token-At {
    param([int]$X, [int]$Y)
    $f = $fg[$X][$Y]
    $b = $bg[$X][$Y]
    if ($f -eq 2) { return "||" }
    if ($f -eq 1 -and $b -eq 2) { return "hecs" }
    if ($f -eq 1 -and $b -eq 3) { return "hece" }
    if ($f -eq 1) { return "he" }
    if ($f -eq 11) { return "e1" }
    if ($f -eq 101 -and $b -eq 2) { return "h1cs" }
    if ($f -eq 101 -and $b -eq 3) { return "h1ce" }
    if ($f -eq 101) { return "h1" }
    if ($f -eq 0 -and $b -eq 2) { return "cs" }
    if ($f -eq 0 -and $b -eq 3) { return "ce" }
    if ($f -eq 0) { return "__" }
    throw "No token mapping for fg=$f bg=$b at ($X,$Y)"
}

$tokens = New-Object System.Collections.Generic.List[string]
for ($row = 0; $row -lt $Size; $row++) {
    $y = $Size - 1 - $row
    for ($x = 0; $x -lt $Size; $x++) {
        $tokens.Add('"' + (Token-At $x $y) + '"')
    }
}

$dir = Split-Path -Parent $OutPath
if ($dir -and -not (Test-Path $dir)) {
    New-Item -ItemType Directory -Path $dir -Force | Out-Null
}

$joined = [string]::Join(",", $tokens)
$content = @"
// Auto-generated by cpp/tools/generate_counter_test_level.ps1.
// Variant: $Variant
// Loaded by cpp/src/main.cpp when BUGMA_N matches this map size.
const COUNTER_TEST_LEVELS = {
  "counter-test-2": { "color": 0, "mode": 1, "map": [$joined] }
};
"@

Set-Content -Encoding UTF8 -Path $OutPath -Value $content
Write-Host "[generated] $OutPath"
Write-Host "[level] counter-test-2 size=${Size}x${Size}"
Write-Host "[variant] $Variant"
